-- Core schema for אשף המסחר.
-- Run once, top to bottom, in the Supabase SQL editor of a FRESH project.
-- Safe to re-run: every statement guards against existing objects.

-- ─────────────────────────────────────────────────────────────
-- 1. plans — subscription tiers shown on the pricing section
-- ─────────────────────────────────────────────────────────────
create table if not exists public.plans (
  id               bigint primary key generated by default as identity,
  name             text not null,
  price            numeric not null default 0,
  is_monthly       boolean not null default true,
  daily_limit      integer not null default 3,
  daily_chat_limit integer not null default 10,
  features         text[] default '{}',
  payment_link     text,
  price_id         text,
  created_at       timestamptz not null default now()
);

-- Plans are public catalogue data: anyone may read, nobody may write.
alter table public.plans enable row level security;
drop policy if exists "plans_public_read" on public.plans;
create policy "plans_public_read" on public.plans for select using (true);

-- Seed. id 1 must exist: it is the tier every new signup lands on.
insert into public.plans (id, name, price, is_monthly, daily_limit, daily_chat_limit, features)
values
  (1, 'חינם',   0,   true,  3,   10,  array['3 ניתוחים ביום','ניתוח טכני בסיסי','גישה למחשבון']),
  (2, 'בסיסי',  99,  true,  20,  50,  array['20 ניתוחים ביום','ניתוח טכני מלא','יומן עסקאות','תמיכה במייל']),
  (3, 'מקצועי', 199, true,  100, 200, array['100 ניתוחים ביום','ניתוח מתקדם','יומן עסקאות','התראות בזמן אמת','תמיכה מועדפת']),
  (4, 'בסיסי שנתי',  831,  false, 20,  50,  array['20 ניתוחים ביום','חיסכון של 30%','ניתוח טכני מלא','יומן עסקאות']),
  (5, 'מקצועי שנתי', 1671, false, 100, 200, array['100 ניתוחים ביום','חיסכון של 30%','ניתוח מתקדם','יומן עסקאות','תמיכה מועדפת'])
on conflict (id) do nothing;

-- Keep the identity sequence ahead of the seeded ids.
select setval(pg_get_serial_sequence('public.plans','id'), greatest((select max(id) from public.plans), 1));

-- ─────────────────────────────────────────────────────────────
-- 2. user_profiles — one row per user, holds their plan
-- ─────────────────────────────────────────────────────────────
create table if not exists public.user_profiles (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null unique references auth.users(id) on delete cascade,
  name                text,
  avatar_url          text,
  plan_id             bigint references public.plans(id),
  recurring_is_active boolean not null default false,
  disable_date        timestamptz,
  created_at          timestamptz not null default now()
);

create index if not exists user_profiles_user_idx on public.user_profiles (user_id);

alter table public.user_profiles enable row level security;
drop policy if exists "profiles_select_own" on public.user_profiles;
create policy "profiles_select_own" on public.user_profiles
  for select using (auth.uid() = user_id);
drop policy if exists "profiles_update_own" on public.user_profiles;
create policy "profiles_update_own" on public.user_profiles
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Every new signup needs a profile immediately, otherwise the first API call
-- reports "No plan found". A trigger is the only place that reliably fires for
-- both email signups and Google OAuth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_profiles (user_id, name, avatar_url, plan_id)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url',
    1
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Backfill anyone who signed up before this trigger existed.
insert into public.user_profiles (user_id, name, plan_id)
select u.id, split_part(u.email, '@', 1), 1
from auth.users u
left join public.user_profiles p on p.user_id = u.id
where p.user_id is null;

-- ─────────────────────────────────────────────────────────────
-- 3. analyses — every chart the user has had analysed
-- ─────────────────────────────────────────────────────────────
create table if not exists public.analyses (
  id         bigint primary key generated by default as identity,
  user_id    uuid not null references auth.users(id) on delete cascade,
  asset_name text,
  type       text,
  analysis   text,
  image      text,
  created_at timestamptz not null default now()
);

create index if not exists analyses_user_created_idx on public.analyses (user_id, created_at desc);

alter table public.analyses enable row level security;
drop policy if exists "analyses_select_own" on public.analyses;
create policy "analyses_select_own" on public.analyses
  for select using (auth.uid() = user_id);
drop policy if exists "analyses_insert_own" on public.analyses;
create policy "analyses_insert_own" on public.analyses
  for insert with check (auth.uid() = user_id);
drop policy if exists "analyses_delete_own" on public.analyses;
create policy "analyses_delete_own" on public.analyses
  for delete using (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 4. user_requests — one row per analysis, drives the daily quota
-- ─────────────────────────────────────────────────────────────
create table if not exists public.user_requests (
  id         bigint primary key generated by default as identity,
  user_id    uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists user_requests_user_created_idx on public.user_requests (user_id, created_at desc);

alter table public.user_requests enable row level security;
drop policy if exists "requests_select_own" on public.user_requests;
create policy "requests_select_own" on public.user_requests
  for select using (auth.uid() = user_id);
drop policy if exists "requests_insert_own" on public.user_requests;
create policy "requests_insert_own" on public.user_requests
  for insert with check (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 5. Storage bucket for uploaded chart images
-- ─────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

drop policy if exists "images_public_read" on storage.objects;
create policy "images_public_read" on storage.objects
  for select using (bucket_id = 'images');

drop policy if exists "images_auth_upload" on storage.objects;
create policy "images_auth_upload" on storage.objects
  for insert with check (bucket_id = 'images' and auth.role() = 'authenticated');
